services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      USE_DOCKER: "true"
      REST_PROTOCOL: "http"
      REST_HOST: "host.docker.internal"
      REST_PORT: "4001"
      WS_PROTOCOL: "ws"
      WS_HOST: "host.docker.internal"
      WS_PORT: "4000"
